name: Build and Push ECS image

on:
  push:
    branches: [main]
    paths:
      - 'worker/**'
      - 'video_transcribe/**'
      - '.github/workflows/push-audio-clean.yml'

env:
  AWS_REGION: us-east-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        include:
          - dir: worker
            repo: 711556655801.dkr.ecr.us-east-1.amazonaws.com/tamma-dev-audio-clean
          - dir: video_transcribe
            repo: 711556655801.dkr.ecr.us-east-1.amazonaws.com/tamma-dev-video-transcribe


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::711556655801:role/github-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${{ matrix.repo }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ matrix.repo }}:latest ./${{ matrix.dir }}
          docker push ${{ matrix.repo }}:latest
